apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-prometheus-deployment
spec:
  selector:
    matchLabels:
      app: node-prometheus
  replicas: 3
  template:
    metadata:
      labels:
        app: node-prometheus
    spec:
      containers:
        - name: node-prometheus
          image: docker.io/sgdreamer7/node-prometheus:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  name: node-prometheus-service
spec:
  type: LoadBalancer
  selector:
    app: node-prometheus
  ports:
    - port: 8080
      name: http
